namespace TubeOrchestrator.Core.Agents.Models;

/// <summary>
/// SEO metadata generated by the SEO Specialist Agent
/// </summary>
public class SeoMetadata
{
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public List<string> Tags { get; set; } = new();
    public string ThumbnailSuggestion { get; set; } = string.Empty;
}
